import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello
      <button onClick={() => router.push("/login")}>Login</button>
      <button onClick={() => router.push("/home/dashboard")}>Home</button>
    </div>
  );
}
